# Generated by Django 4.2.3 on 2023-07-26 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
    ]
